[package]
name = "kv"
version = "0.1.0"
edition = "2021"
publish = false

[lints]
workspace = true

[dependencies]
slugger = { path = "../slugger" }

miette.workspace = true
thiserror.workspace = true
futures.workspace = true

fred = { version = "9.1" }
smallvec = "1.13.2"

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }

