
[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.dependencies]
async-trait = { version = "0.1" }
serde = { version = "1", features = [ "derive" ] }
thiserror = { version = "1" }
tokio = { version = "1" }
