services:
  # sourced from: https://tikv.org/docs/4.0/tasks/deploy/docker/
 
  tikv1:
    image: pingcap/tikv:latest
    container_name: tikv1
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./tikv_data:/data
    command: --addr="0.0.0.0:20160" --advertise-addr="127.0.0.1:20160" --data-dir="/data/tikv1" --pd="127.0.0.1:2379"
      
  pd1:
    image: pingcap/pd:latest
    container_name: pd1
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./tikv_data:/data
    command: --name="pd1" --data-dir="/data/pd1" --client-urls="http://0.0.0.0:2379" --advertise-client-urls="http://127.0.0.1:2379" --peer-urls="http://0.0.0.0:2380" --advertise-peer-urls="http://127.0.0.1:2380" --initial-cluster="pd1=http://127.0.0.1:2380"

