[package]
name = "slugger"
version = "0.1.0"
edition = "2021"
publish = false

[lints]
workspace = true

[dependencies]
serde.workspace = true
slug = { version = "0.1" }
nutype = { workspace = true, features = [ "serde" ] }
