[package]
name = "repos"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
models = { path = "../models" }
db = { path = "../db" }
storage = { path = "../storage" }

async-trait.workspace = true
miette.workspace = true
tracing.workspace = true

[lints]
workspace = true
