[package]
name = "fetcher"
version = "0.1.0"
edition = "2021"

[dependencies]
storage = { path = "../storage" }

axum.workspace = true
tokio = { workspace = true, features = [ "rt", "rt-multi-thread" ] }

tracing.workspace = true
tracing-subscriber.workspace = true
