[package]
name = "jobs"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
serde.workspace = true
miette.workspace = true

apalis = { workspace = true, features = [ "redis" ] }
redis = { version = "0.25" }
