[package]
name = "stream-tools"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
dvf = { path = "../dvf" }

tokio = { workspace = true, features = [ "rt", "io-util", "sync" ] }

[lints]
workspace = true
