[package]
name = "crunch"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
dvf = { path = "../dvf" }
stream-tools = { path = "../stream-tools" }

snap = { version = "1.1" }

[lints]
workspace = true
