[package]
name = "db"
version = "0.1.0"
edition = "2021"
publish = false

[lints]
workspace = true

[dependencies]
kv = { path = "../kv", features = [ "tikv" ] }
models = { path = "../models" }
slugger = { path = "../slugger" }

miette.workspace = true
tracing.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }
