[package]
name = "db"
version = "0.1.0"
edition = "2021"
publish = false

[lints]
workspace = true

[dependencies]
models = { path = "../models" }
slugger = { path = "../slugger" }

# serde.workspace = true
miette.workspace = true
tracing.workspace = true

surrealdb = { workspace = true, features = [ "protocol-ws" ] }
surrealdb-migrations = { version = "1.5" }

include_dir = { version = "0.7" }
