
CREATE token:01J53ZA38PS1P5KWCE4FMG58F0 CONTENT {
  nickname: "omnitoken",
  secret: "ZvKA5D29dgvpUjdyQa6fTnKEI02i-Qm1N-fJZuQfbyRq7AvXBZI6MA8flxSuwE4l",
  perms: [
    {
      "store_id": store:01J53YYCCJW4B4QBM1CG0CHAMP,
      "permission": "Read",
    },
    {
      "store_id": store:01J53YYCCJW4B4QBM1CG0CHAMP,
      "permission": "Write",
    },
  ],
  owner: user:01J53N6ARQGFTBQ41T25TAJ949,
  org: org:01J53FHN8TQXTQ2JEHNX56GCTN,
};
